// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/profile/v1/profile.proto

package profilev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetProfileRequest is the request message for GetProfile.
type GetProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id is the unique identifier for the user whose profile is requested.
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_proto_profile_v1_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_v1_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_v1_profile_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetProfileResponse is the response message for GetProfile.
type GetProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id is the unique identifier of the user.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// display_name is the user's display name.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// email is the user's email address.
	Email         string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_proto_profile_v1_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_v1_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_v1_profile_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProfileResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GetProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_proto_profile_v1_profile_proto protoreflect.FileDescriptor

const file_proto_profile_v1_profile_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/profile/v1/profile.proto\x12\n" +
	"profile.v1\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"f\n" +
	"\x12GetProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email2\xae\x01\n" +
	"\x0eProfileService\x12K\n" +
	"\n" +
	"GetProfile\x12\x1d.profile.v1.GetProfileRequest\x1a\x1e.profile.v1.GetProfileResponse\x12O\n" +
	"\fListProfiles\x12\x1d.profile.v1.GetProfileRequest\x1a\x1e.profile.v1.GetProfileResponse0\x01BCZAgithub.com/Zura16/Reusable-Go-Services/proto/profile/v1;profilev1b\x06proto3"

var (
	file_proto_profile_v1_profile_proto_rawDescOnce sync.Once
	file_proto_profile_v1_profile_proto_rawDescData []byte
)

func file_proto_profile_v1_profile_proto_rawDescGZIP() []byte {
	file_proto_profile_v1_profile_proto_rawDescOnce.Do(func() {
		file_proto_profile_v1_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_profile_v1_profile_proto_rawDesc), len(file_proto_profile_v1_profile_proto_rawDesc)))
	})
	return file_proto_profile_v1_profile_proto_rawDescData
}

var file_proto_profile_v1_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_profile_v1_profile_proto_goTypes = []any{
	(*GetProfileRequest)(nil),  // 0: profile.v1.GetProfileRequest
	(*GetProfileResponse)(nil), // 1: profile.v1.GetProfileResponse
}
var file_proto_profile_v1_profile_proto_depIdxs = []int32{
	0, // 0: profile.v1.ProfileService.GetProfile:input_type -> profile.v1.GetProfileRequest
	0, // 1: profile.v1.ProfileService.ListProfiles:input_type -> profile.v1.GetProfileRequest
	1, // 2: profile.v1.ProfileService.GetProfile:output_type -> profile.v1.GetProfileResponse
	1, // 3: profile.v1.ProfileService.ListProfiles:output_type -> profile.v1.GetProfileResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_profile_v1_profile_proto_init() }
func file_proto_profile_v1_profile_proto_init() {
	if File_proto_profile_v1_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_profile_v1_profile_proto_rawDesc), len(file_proto_profile_v1_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_profile_v1_profile_proto_goTypes,
		DependencyIndexes: file_proto_profile_v1_profile_proto_depIdxs,
		MessageInfos:      file_proto_profile_v1_profile_proto_msgTypes,
	}.Build()
	File_proto_profile_v1_profile_proto = out.File
	file_proto_profile_v1_profile_proto_goTypes = nil
	file_proto_profile_v1_profile_proto_depIdxs = nil
}
